### ISSUE TITLE
Another approach to Math.abs()

### ISSUE THREAD

**Issue by scottwar34** [sherxon/AlgoDS#22]
hi I like your code for ReverseInteger. Why do you use the Math.abs()?  Here is another approach with less code:  
```
public int reverse(int x) {
    int rev = 0;
    while(x != 0){
        rev = rev*10 + x%10;
        x = x/10;
    }
 
    return rev;
}
```

**Comment by sherxon** [comment]
hi Nice Solution, did you test x = -12 and x= 2147483647 cases?
