### ISSUE TITLE
CycleDetection

### ISSUE THREAD

**Issue by aoyuanbo** [sherxon/AlgoDS#42]
Whether or not there is a cycle, this program always returns true after running
` for (Integer neighbor : graph.getNeighbors(start)) {

            if(visited.contains(neighbor) && !exited.contains(neighbor)) return true;

            if(!visited.contains(neighbor) && dfs(neighbor)) return true;
        }`

**Comment by sherxon** [comment]
Can you give any sample directed graph that returns true if there is no cycle?

**Comment by aoyuanbo** [comment]
I know what happened, I use the undirected graph.
