### ISSUE TITLE
Overflow in ContainsDuplicate

### ISSUE THREAD

**Issue by berezovskyi** [sherxon/AlgoDS#7]
https://github.com/sherxon/AlgoDS/blob/master/src/interviewquestions/easy/ContainsDuplicate.java#L17:

        for (int i : nums) {
            if (!set.add(-2 * i)) return true;
        }

Why multiply by -2?

See https://repl.it/HBRv/0: `new int[] {2147483646, -2}` contains duplicates.

**Comment by sherxon** [comment]
fixed,
